name: open_assistant
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - atlassian-python-api
  - beautifulsoup4
  - boto3
  - claude-code-sdk
  - dateparser
  - gh
  - mistune
  - mypy
  - plotly
  - pytest
  - python-dotenv
  - requests
  - ruff
  - uv
  - xenon
  - pip
  - pip:
      - amplitude-experiment
      - tempo-api-python-client
